import React, { useState, useEffect, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  SafeAreaView,
  ScrollView,
  TextInput,
  Modal,
  Animated,
} from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { Colors } from '@/constants/Colors';
import { getAllSessions, addProgressLog, updateStreak } from '@/utils/storage';
import { CoachingSession } from '@/types';

export default function ActionPlanScreen() {
  const router = useRouter();
  const { sessionId } = useLocalSearchParams<{ sessionId: string }>();
  const [session, setSession] = useState<CoachingSession | null>(null);
  const [showLogModal, setShowLogModal] = useState(false);
  const [progressNote, setProgressNote] = useState('');
  const [showSuccess, setShowSuccess] = useState(false);
  const [newStreakCount, setNewStreakCount] = useState(0);

  const buttonScale = useRef(new Animated.Value(1)).current;
  const successScale = useRef(new Animated.Value(0)).current;
  const fireScale = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    loadSession();
  }, [sessionId]);

  const loadSession = async () => {
    const sessions = await getAllSessions();
    const found = sessions.find((s) => s.id === sessionId);
    if (found) {
      setSession(found);
    }
  };

  const handleLogProgress = async () => {
    if (!progressNote.trim() || !session) return;

    // Haptic feedback on button press
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);

    // Button press animation
    Animated.sequence([
      Animated.timing(buttonScale, {
        toValue: 0.95,
        duration: 100,
        useNativeDriver: true,
      }),
      Animated.timing(buttonScale, {
        toValue: 1,
        duration: 100,
        useNativeDriver: true,
      }),
    ]).start();

    await addProgressLog(session.id, progressNote);
    const newStreak = await updateStreak();
    setNewStreakCount(newStreak);

    // Show success animation
    setShowSuccess(true);

    // Animate success checkmark
    Animated.spring(successScale, {
      toValue: 1,
      tension: 50,
      friction: 7,
      useNativeDriver: true,
    }).start();

    // Animate fire icon with bounce
    setTimeout(() => {
      Animated.spring(fireScale, {
        toValue: 1,
        tension: 40,
        friction: 5,
        useNativeDriver: true,
      }).start();
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    }, 300);

    // Auto-dismiss after animation
    setTimeout(() => {
      setShowLogModal(false);
      setShowSuccess(false);
      setProgressNote('');
      successScale.setValue(0);
      fireScale.setValue(0);
      router.replace('/(tabs)');
    }, 2500);
  };

  if (!session) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.loadingContainer}>
          <Text>Loading...</Text>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <View style={styles.header}>
          <TouchableOpacity
            style={styles.backButton}
            onPress={() => router.back()}
          >
            <Ionicons name="arrow-back" size={24} color={Colors.navy} />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Your Action Plan</Text>
          <View style={{ width: 40 }} />
        </View>

        <View style={styles.content}>
          <View style={styles.challengeCard}>
            <Text style={styles.challengeLabel}>BASED ON YOUR CHALLENGE</Text>
            <Text style={styles.challengeText}>{session.challenge}</Text>
          </View>

          <View style={styles.stepsContainer}>
            {session.actionPlan.map((step, index) => (
              <View key={index} style={styles.stepCard}>
                <View style={styles.stepIconContainer}>
                  <Ionicons
                    name="checkmark-circle"
                    size={24}
                    color={Colors.success}
                  />
                </View>
                <View style={styles.stepContent}>
                  <Text style={styles.stepNumber}>Step {index + 1}</Text>
                  <Text style={styles.stepText}>{step}</Text>
                </View>
              </View>
            ))}
          </View>

          <View style={styles.aiNote}>
            <Ionicons name="information-circle" size={20} color={Colors.primary} />
            <Text style={styles.aiNoteText}>
              3-5 actionable steps generated by Newell AI.
            </Text>
          </View>

          <TouchableOpacity
            style={styles.logButton}
            onPress={() => setShowLogModal(true)}
            activeOpacity={0.8}
          >
            <Text style={styles.logButtonText}>Log Daily Progress</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>

      {/* Progress Log Modal */}
      <Modal
        visible={showLogModal}
        animationType="slide"
        transparent={true}
        onRequestClose={() => {
          setShowLogModal(false);
          setShowSuccess(false);
          setProgressNote('');
        }}
      >
        <TouchableOpacity
          style={styles.modalOverlay}
          activeOpacity={1}
          onPress={() => {
            setShowLogModal(false);
            setShowSuccess(false);
            setProgressNote('');
          }}
        >
          <TouchableOpacity
            activeOpacity={1}
            onPress={(e) => e.stopPropagation()}
          >
            <View style={styles.modalContent}>
              {!showSuccess ? (
                <>
                  <View style={styles.modalHeader}>
                    <View style={styles.modalTitleContainer}>
                      <View style={styles.modalIconContainer}>
                        <Ionicons name="create" size={24} color={Colors.success} />
                      </View>
                      <Text style={styles.modalTitle}>Log Your Win</Text>
                    </View>
                    <TouchableOpacity
                      onPress={() => {
                        setShowLogModal(false);
                        setProgressNote('');
                      }}
                      style={styles.closeButton}
                    >
                      <Ionicons name="close" size={28} color={Colors.navy} />
                    </TouchableOpacity>
                  </View>

                  <Text style={styles.modalSubtitle}>
                    What did you accomplish today? 🎯
                  </Text>

                  <View style={styles.inputContainer}>
                    <TextInput
                      style={styles.modalInput}
                      placeholder="e.g., Completed 2 LeetCode problems, updated my resume, reached out to 3 recruiters..."
                      placeholderTextColor={Colors.mediumGray}
                      multiline
                      numberOfLines={5}
                      value={progressNote}
                      onChangeText={setProgressNote}
                      textAlignVertical="top"
                      autoFocus
                    />
                  </View>

                  <Animated.View
                    style={[
                      styles.submitButtonContainer,
                      { transform: [{ scale: buttonScale }] },
                    ]}
                  >
                    <TouchableOpacity
                      style={[
                        styles.modalButton,
                        !progressNote.trim() && styles.modalButtonDisabled,
                      ]}
                      onPress={handleLogProgress}
                      disabled={!progressNote.trim()}
                      activeOpacity={0.8}
                    >
                      <Ionicons
                        name="checkmark-circle"
                        size={24}
                        color={Colors.white}
                      />
                      <Text style={styles.modalButtonText}>Log Progress</Text>
                    </TouchableOpacity>
                  </Animated.View>
                </>
              ) : (
                <View style={styles.successContainer}>
                  <Animated.View
                    style={[
                      styles.successIcon,
                      { transform: [{ scale: successScale }] },
                    ]}
                  >
                    <Ionicons
                      name="checkmark-circle"
                      size={80}
                      color={Colors.success}
                    />
                  </Animated.View>
                  <Text style={styles.successTitle}>Progress Logged!</Text>
                  <View style={styles.streakContainer}>
                    <Animated.Text
                      style={[
                        styles.fireIcon,
                        { transform: [{ scale: fireScale }] },
                      ]}
                    >
                      🔥
                    </Animated.Text>
                    <Text style={styles.streakText}>
                      {newStreakCount} Day Streak!
                    </Text>
                  </View>
                  <Text style={styles.successSubtitle}>
                    Keep up the amazing work! 💪
                  </Text>
                </View>
              )}
            </View>
          </TouchableOpacity>
        </TouchableOpacity>
      </Modal>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContent: {
    flexGrow: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.lightGray,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: Colors.navy,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
  },
  challengeCard: {
    backgroundColor: '#FFF3E0',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  challengeLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.mediumGray,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  challengeText: {
    fontSize: 14,
    color: Colors.navy,
    lineHeight: 21,
    fontWeight: '500',
  },
  stepsContainer: {
    marginBottom: 20,
  },
  stepCard: {
    backgroundColor: Colors.white,
    borderRadius: 12,
    paddingVertical: 18,
    paddingHorizontal: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  stepIconContainer: {
    marginRight: 14,
    marginTop: 1,
  },
  stepContent: {
    flex: 1,
  },
  stepNumber: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.success,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  stepText: {
    fontSize: 15,
    color: Colors.navy,
    lineHeight: 24,
    fontWeight: '400',
  },
  aiNote: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F7FF',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 20,
  },
  aiNoteText: {
    fontSize: 12,
    color: Colors.primary,
    marginLeft: 10,
    flex: 1,
    lineHeight: 18,
  },
  logButton: {
    backgroundColor: Colors.success,
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 24,
    alignItems: 'center',
    shadowColor: Colors.success,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
  },
  logButtonText: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'flex-end',
    paddingTop: 100,
  },
  modalContent: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 28,
    paddingBottom: 48,
    minHeight: 420,
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  modalTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  modalIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#E8F5E9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: Colors.navy,
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.background,
  },
  modalSubtitle: {
    fontSize: 16,
    color: Colors.navy,
    marginBottom: 24,
    lineHeight: 22,
    marginLeft: 60,
  },
  inputContainer: {
    marginBottom: 24,
  },
  modalInput: {
    backgroundColor: Colors.background,
    borderRadius: 16,
    padding: 20,
    fontSize: 16,
    color: Colors.navy,
    minHeight: 140,
    borderWidth: 2,
    borderColor: 'transparent',
    lineHeight: 24,
  },
  submitButtonContainer: {
    marginTop: 8,
  },
  modalButton: {
    backgroundColor: Colors.success,
    borderRadius: 20,
    paddingVertical: 20,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    shadowColor: Colors.success,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 8,
  },
  modalButtonDisabled: {
    backgroundColor: Colors.lightGray,
    shadowOpacity: 0,
    elevation: 0,
  },
  modalButtonText: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  successContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  successIcon: {
    marginBottom: 24,
  },
  successTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: Colors.navy,
    marginBottom: 24,
  },
  streakContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF3E0',
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 32,
    marginBottom: 16,
  },
  fireIcon: {
    fontSize: 40,
    marginRight: 12,
  },
  streakText: {
    fontSize: 24,
    fontWeight: '700',
    color: Colors.navy,
  },
  successSubtitle: {
    fontSize: 16,
    color: Colors.mediumGray,
    textAlign: 'center',
  },
});
