import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  SafeAreaView,
  ScrollView,
  TextInput,
  Modal,
  Alert,
} from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Colors } from '@/constants/Colors';
import { getAllSessions, addProgressLog, updateStreak } from '@/utils/storage';
import { CoachingSession } from '@/types';

export default function ActionPlanScreen() {
  const router = useRouter();
  const { sessionId } = useLocalSearchParams<{ sessionId: string }>();
  const [session, setSession] = useState<CoachingSession | null>(null);
  const [showLogModal, setShowLogModal] = useState(false);
  const [progressNote, setProgressNote] = useState('');

  useEffect(() => {
    loadSession();
  }, [sessionId]);

  const loadSession = async () => {
    const sessions = await getAllSessions();
    const found = sessions.find((s) => s.id === sessionId);
    if (found) {
      setSession(found);
    }
  };

  const handleLogProgress = async () => {
    if (!progressNote.trim() || !session) return;

    await addProgressLog(session.id, progressNote);
    const newStreak = await updateStreak();

    setShowLogModal(false);
    Alert.alert(
      'Progress Logged!',
      `Great work! Your streak is now ${newStreak} days. Keep it up!`,
      [
        {
          text: 'OK',
          onPress: () => router.replace('/(tabs)'),
        },
      ]
    );
  };

  if (!session) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.loadingContainer}>
          <Text>Loading...</Text>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <View style={styles.header}>
          <TouchableOpacity
            style={styles.backButton}
            onPress={() => router.back()}
          >
            <Ionicons name="arrow-back" size={24} color={Colors.navy} />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Your Action Plan</Text>
          <View style={{ width: 40 }} />
        </View>

        <View style={styles.content}>
          <View style={styles.challengeCard}>
            <Text style={styles.challengeLabel}>Based on your challenge:</Text>
            <Text style={styles.challengeText}>{session.challenge}</Text>
          </View>

          <View style={styles.stepsContainer}>
            {session.actionPlan.map((step, index) => (
              <View key={index} style={styles.stepCard}>
                <View style={styles.stepIconContainer}>
                  <Ionicons
                    name="checkmark-circle"
                    size={24}
                    color={Colors.success}
                  />
                </View>
                <View style={styles.stepContent}>
                  <Text style={styles.stepNumber}>Step {index + 1}</Text>
                  <Text style={styles.stepText}>{step}</Text>
                </View>
              </View>
            ))}
          </View>

          <View style={styles.aiNote}>
            <Ionicons name="information-circle" size={20} color={Colors.primary} />
            <Text style={styles.aiNoteText}>
              3-5 actionable steps generated by Newell AI.
            </Text>
          </View>

          <TouchableOpacity
            style={styles.logButton}
            onPress={() => setShowLogModal(true)}
            activeOpacity={0.8}
          >
            <Text style={styles.logButtonText}>Log Daily Progress</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>

      {/* Progress Log Modal */}
      <Modal
        visible={showLogModal}
        animationType="slide"
        transparent={true}
        onRequestClose={() => setShowLogModal(false)}
      >
        <View style={styles.modalOverlay}>
          <View style={styles.modalContent}>
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle}>Log Your Progress</Text>
              <TouchableOpacity onPress={() => setShowLogModal(false)}>
                <Ionicons name="close" size={28} color={Colors.navy} />
              </TouchableOpacity>
            </View>

            <Text style={styles.modalSubtitle}>
              Record a quick note about your progress today:
            </Text>

            <TextInput
              style={styles.modalInput}
              placeholder="e.g., Completed one LeetCode problem, spent 1 hour studying..."
              placeholderTextColor={Colors.mediumGray}
              multiline
              numberOfLines={4}
              value={progressNote}
              onChangeText={setProgressNote}
              textAlignVertical="top"
              autoFocus
            />

            <TouchableOpacity
              style={[
                styles.modalButton,
                !progressNote.trim() && styles.modalButtonDisabled,
              ]}
              onPress={handleLogProgress}
              disabled={!progressNote.trim()}
            >
              <Text style={styles.modalButtonText}>Save Progress</Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContent: {
    flexGrow: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.lightGray,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: Colors.navy,
  },
  content: {
    padding: 24,
  },
  challengeCard: {
    backgroundColor: '#FFF3E0',
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
  },
  challengeLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.mediumGray,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  challengeText: {
    fontSize: 14,
    color: Colors.navy,
    lineHeight: 20,
  },
  stepsContainer: {
    marginBottom: 24,
  },
  stepCard: {
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  stepIconContainer: {
    marginRight: 12,
    paddingTop: 2,
  },
  stepContent: {
    flex: 1,
  },
  stepNumber: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.success,
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  stepText: {
    fontSize: 14,
    color: Colors.navy,
    lineHeight: 20,
  },
  aiNote: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F7FF',
    borderRadius: 8,
    padding: 12,
    marginBottom: 24,
  },
  aiNoteText: {
    fontSize: 12,
    color: Colors.primary,
    marginLeft: 8,
    flex: 1,
  },
  logButton: {
    backgroundColor: Colors.success,
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    shadowColor: Colors.success,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
  },
  logButtonText: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: Colors.navy,
  },
  modalSubtitle: {
    fontSize: 14,
    color: Colors.mediumGray,
    marginBottom: 16,
  },
  modalInput: {
    backgroundColor: Colors.background,
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: Colors.navy,
    minHeight: 120,
    marginBottom: 16,
  },
  modalButton: {
    backgroundColor: Colors.success,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  modalButtonDisabled: {
    backgroundColor: Colors.lightGray,
  },
  modalButtonText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
});
